language: node_js
node_js:
  - "0.10"
before_install: npm install -g grunt-cli
install: npm install
before_script:
  - npm run-script bower
  - npm run-script bower_for_test
  - grunt clean concat:all
